import { ADMIN_MANAGEMENT, CUSTOMER_PERMISSIONS, FINANCIAL_PERMISSIONS, INVENTORY_MGT_PERMISSIONS, LOGIN_ATTEMPT_PERMISSIONS, SALES_PERMISSIONS, STAFF_PERMISSIONS } from "../const/permissons";


export const PAGE_PERMISSIONS: Record<string, string[]> = {
  "/dashboard": [
    INVENTORY_MGT_PERMISSIONS.VIEW_INVENTORY,
    FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    CUSTOMER_PERMISSIONS.VIEW_CUSTOMER,
    STAFF_PERMISSIONS.VIEW_STAFF,
    ADMIN_MANAGEMENT.VIEW_SETTINGS,
    LOGIN_ATTEMPT_PERMISSIONS.VIEW_LOGIN_ATTEMPTS,
  ], 

  "/inventory": [
    INVENTORY_MGT_PERMISSIONS.VIEW_INVENTORY,
  ],

  "/sales": [
    SALES_PERMISSIONS.VIEW_SALES,
  ],

  "/expenses": [
    FINANCIAL_PERMISSIONS.VIEW_EXPENSES,
  ],

  "/customers": [
    CUSTOMER_PERMISSIONS.VIEW_CUSTOMER,
  ],

  "/staffs": [
    STAFF_PERMISSIONS.VIEW_STAFF,
  ],

  "/settings": [
    ADMIN_MANAGEMENT.VIEW_SETTINGS,
  ],
};
